### ISSUE TITLE
Trie is no longer DeepEqual after v1.5.5

### ISSUE THREAD

**Issue by brackendawson** [seancfoley/ipaddress-go#10]
We upgraded from v1.5.4 to v1.5.5 and discovered that equal Tries are no longer deeply equal. Unexpected breaking change?

# Steps
main.go
```go
package main

import (
	"fmt"
	"reflect"

	"github.com/seancfoley/ipaddress-go/ipaddr"
)

func main() {
	i := ipaddr.NewIPv4AddressTrie()
	j := ipaddr.NewIPv4AddressTrie()
	i.Add(ipaddr.NewIPAddressString("192.168.1.0/8").GetAddress().ToIPv4())
	j.Add(ipaddr.NewIPAddressString("192.168.1.0/8").GetAddress().ToIPv4())
	fmt.Println(reflect.DeepEqual(i, j))
	fmt.Println(i.Equal(j))
}
```

working go.mod
```go
module play.ground

go 1.21.4

require github.com/seancfoley/ipaddress-go v1.5.4

require github.com/seancfoley/bintree v1.2.1 // indirect
```

not working go.mod
```go
module play.ground

go 1.21.4

require github.com/seancfoley/ipaddress-go v1.5.5

require github.com/seancfoley/bintree v1.2.3 // indirect
```

# Expected output
```
true
true
```

# Actual output
```
false
true
```

**Comment by seancfoley** [comment]
I've confirmed your test.  

Here is my summary at this time:  IPAddress types do not guarantee that reflect.DeepEqual will work.  It uses golang equality and compares absolutely everything, including things that are irrelevant and should not be compared.  That is why tries and addresses have Equal methods.

The fact that in v1.5.4 you get true for reflect.DeepEqual, well that is not really reliable.  You can probably call a method on one of the two addresses you put into the trie, and it will become false. 

I am a little curious what is the difference here between v1.5.4 and v1.5.5 that changes the result of reflect.DeepEqual, so I might try to find out. 

But really, I do not consider this a bug, because DeepEqual is not expected to work in general with any of the types in IPAddress.  That is why the methods Equal for tries, addresses and most types (and DeepEqual with associative tries) is provided.

**Comment by seancfoley** [comment]
I have taken a look at what caused this behaviour change.  The behaviour was changed when I [added a sync.Pool for root nodes for performance reasons](https://github.com/seancfoley/bintree/blob/master/tree/bintreenode.go#L141) to improve trie performance.  I don't know if it is possible to make that work with reflect.DeepEqual - the generic types make the pool more difficult to share.  Even if I could, there is also a changetracker type in there that might also cause reflect.DeepEqual to not work on occasion.

**Comment by seancfoley** [comment]
This code shows you cannot use reflect.DeepEqual in version 1.5.4 either:
```go
i := ipaddr.NewIPv4AddressTrie()
j := ipaddr.NewIPv4AddressTrie()
ai := ipaddr.NewIPAddressString("192.168.1.0/24").GetAddress().ToIPv4()
aj := ipaddr.NewIPAddressString("192.168.1.0/24").GetAddress().ToIPv4()
ak := ipaddr.NewIPAddressString("192.168.2.0/24").GetAddress().ToIPv4()
i.Add(ai)
j.Add(aj)
i.Equal(j)
i.Add(ak)
i.Remove(ak)
fmt.Println("reflect.DeepEqual", reflect.DeepEqual(i, j))
fmt.Println("Equal", i.Equal(j))
```
```
reflect.DeepEqual false
Equal true
```
reflect.DeepEqual can return false when two tries have the same trie data, or when two addresses have the same address data.  This is [not uncommon in go](https://stackoverflow.com/questions/75824869/reflect-deepequal-not-working-on-timestamp-comparison).  reflect.DeepEqual should only be used with types when it is known that it provides the desired results.

With tries in this library, there is functionality to improve lookup performance, and functionality to detect when a trie has been changed while iterating through it, and the data fields required for these features are parsed by reflect.DeepEqual, possibly changing the results.  With addresses, there are also circumstances when reflect.DeepEqual will not provide the answers one might anticipate.

However, an Equal method is provided for almost all types in this library, and has much better performance anyway.  With associative tries you can also use the trie DeepEqual method.  

With addresses, in addition to Equal, you can convert to and from the AddressKey (or IPAddressKey or other key types) for a given address, and each of the key types are compatible with reflect.DeepEqual.  So, you can put those types in other data types that you wish to compare with reflect.DeepEqual.

So, I do not consider this a bug, nor is there an intent to support reflect.DeepEqual with IPAddress tries or addresses.
