### ISSUE TITLE
MergeToPrefixBlocks Method Merges IPv4 and IPv6 Default Routes Unexpectedly

### ISSUE THREAD

**Issue by SPuerBRead** [seancfoley/ipaddress-go#12]
Hello, I used the MergeToPrefixBlocks method from this library to merge multiple subnets. However, during actual use, I found the following issue with the code:

`var a []*ipaddr.IPAddress
a = append(a, ipaddr.NewIPAddressString("0.0.0.0/0").GetAddress(), ipaddr.NewIPAddressString("0::0/0").GetAddress(), ipaddr.NewIPAddressString("::/0").GetAddress())
fmt.Println(a[0].MergeToPrefixBlocks(a[1:]...))`

The returned result is [0.0.0.0/0]. Shouldn't it return [0.0.0.0/0, 0::0/0] or [0.0.0.0/0, ::/0], which would separately represent the entirety of IPv4 and IPv6? Is there any configuration that would allow me to obtain this result?

Thank you very much to the author for developing this library.

**Comment by seancfoley** [comment]
You're welcome.

This result was intentional behaviour, see [the godoc](https://pkg.go.dev/github.com/seancfoley/ipaddress-go/ipaddr#IPAddress.MergeToPrefixBlocks): "Arguments that are not the same IP version are ignored"

When merging both IPv4 and IPv6, it really ends up being two separate merge operations.  It doesn't actually make logical sense to be "merging" addresses of two different versions/sizes.  But if you want to do both merge operations, you can do so:
```go
// check for other IP versions
var result []*ipaddr.IPAddress
for i := range a {
	if !a[i].GetIPVersion().Equal(a[0].GetIPVersion()) {
		result = a[i].MergeToPrefixBlocks(a...)
		break
	}
}
// merge both IP versions
result = append(a[0].MergeToPrefixBlocks(a...), result...)
fmt.Println(result)
```
```
[0.0.0.0/0 ::/0]
```

**Comment by seancfoley** [comment]
For this, you can use the new [MergeToPrefixBlocks](https://pkg.go.dev/github.com/seancfoley/ipaddress-go/ipaddr#MergeToPrefixBlocks) in version 1.7.0
